### ISSUE TITLE
Add function declaration in grammar

### ISSUE THREAD

**Issue by Embraser01** [Heptabarnak/MapleCompiler#18]
We have to add funtion declaration otherwise this will not wsork : 

```c

void a() {
	b(); // b was not declared
}

void b() {
	a();
}
```

This is link to #17.
We would have to add a rule in the grammar, and then in the visitor,
Add an incomplete `FunctionDefinition` into the symbol table, and complete it with definition.

**Comment by JuCN** [comment]
Done
