### ISSUE TITLE
Use better filename 

### ISSUE THREAD

**Issue by Embraser01** [Heptabarnak/MapleCompiler#39]
For now, generate `sample1.c` give a `sample1.c.s` instead of a nicer `sample1.s`

**Comment by TomBourret** [comment]
J'imagine qu'il faut gérer les systèmes Windows comme Linux ou Unix du coup ?

**Comment by Embraser01** [comment]
Au moins Linux, mais si tu as les deux c'est cool

**Comment by TomBourret** [comment]
Et du coup, rajouter des librairies comme Boost, c'pas le plus opti j'imagine

**Comment by Embraser01** [comment]
Nop, Boost est une très grosse librairie, pour parser un chemin c'est un peu trop 😅
