### ISSUE TITLE
Compléter le StartVisitor

### ISSUE THREAD

**Issue by Embraser01** [Heptabarnak/MapleCompiler#5]
Il faut compléter chaque fonction du visiteur pour créer l'objet adapté.

Pour cela il faudra envoyer dans chaque objet, le `SymbolTable` le plus près. 
Je sais pas comment faire 😢

**Comment by Embraser01** [comment]
Pour faire ça, on peut rajouter une variable SymbolTable dans le visiteur qui correspond à la table la plus proche

**Comment by loicsrz** [comment]
Je m'occupe de visitExprValue

**Comment by Vincegln** [comment]
- [ ] 
- [ ]

**Comment by MrJuju97351** [comment]
I'm doing visitExprBinaryShift

**Comment by Vincegln** [comment]
- [x] visitValue
- [x] visitStart
- [x] visitProgram
- [x] visitExprAdditive
- [x] visitExprValue
- [x] visitExprBinaryShift
- [x] visitExprAffectation
- [x] visitExprBinaryXor
- [x] visitExprBinaryAnd
- [x] visitExprOr
- [x] visitExprUnaryPostfix
- [x] visitExprMultiplicative
- [x] visitExprAccessor
- [x] visitExprAnd
- [x] visitExprParenthesis
- [x] visitExprBinaryOr
- [x] visitExprCompareRelational
- [x] visitExprCompareEquality
- [x] visitExprUnaryPrefix
- [x] visitDeclarationVar
- [x] visitDeclarationTab
- [x] visitDeclaration
- [x] visitDefinitionTab
- [x] visitAssignment
- [x] visitAccessorTab
- [x] visitAccessorVar
- [x] visitAccessorFunction
- [x] visitLeftValue
- [x] visitAccessor
- [x] visitIfStatement
- [x] visitElseStatement
- [x] visitWhileStatement
- [x] visitFunctionDefinition
- [x] visitReturnStatement
- [x] visitBlockFunction
- [x] visitArgumentList
- [x] visitTypeList
- [x] visitBlock
- [x] visitStatement
- [x] visitInstruction

**Comment by Jintus** [comment]
Petit probleme les amis, Program n'existe plus dans notre diag de class donc comment oon gere la visite d'un program ?

**Comment by Embraser01** [comment]
Il appelle directement le visit sur ctx->declaration ou ctx->functionDefinition (je crois)
